import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className="divide-y">
      <Head>
        <title>Yatrana - Inmobiliaria & seguros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="font-sans">
        <h1 className="text-center text-5xl font-bold my-20">
          Welcome to <a className="text-blue-300" href="https://nextjs.org">Next.js with Tailwind CSS!</a>
        </h1>

       
      </main>

      <footer className="flex flex-col justify-center items-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> 
        <p className=''>Design by <a href="https://www.google.com" target="_blank" rel='noreferrer'><span className='text-orange-400 font-bold'>SisifoDev</span></a></p>
      </footer>
    </div>
  )
}

export default Home
